name: build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '46 8 * * 4'

jobs:
  build:
    env:
      CONTRIBUTIONS_REPO: Dash-User-Contributions
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      if: github.ref == 'refs/heads/main'
      with:
        token: ${{ secrets.DASH_USER_CONTRIBUTIONS_PAT }}
        repository: Kapeli/${{ env.CONTRIBUTIONS_REPO }}
        path: ${{ env.CONTRIBUTIONS_REPO }}
    - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: ruby
        bundler-cache: true
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          antora-cache
        key: dump
    - run: |
        go install github.com/technosophos/dashing@172c69f1c58cf6efe5b1813fa06ce29a684b00e4
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: bundle exec rake
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: results
        path: 'results/*'
    - name: create/update branch for PR if there are changes
      if: github.ref == 'refs/heads/main'
      run: |
        set -x

        owner="${{ github.repository_owner }}"
        branch=$(basename "${{ github.repository }}")
        git -C "$CONTRIBUTIONS_REPO" remote add rw "https://github.com/$owner/$CONTRIBUTIONS_REPO"
        if git -C "$CONTRIBUTIONS_REPO" fetch --depth=1 rw "$branch"; then
          git -C "$CONTRIBUTIONS_REPO" branch "$branch" rw/"$branch"
        else
          git -C "$CONTRIBUTIONS_REPO" branch "$branch"
        fi

        changes=()
        changed_from_branch=0
        for src_json_path in results/*/docset.json; do
          dst_rel_json_path="docsets/${src_json_path#*/}"
          dst_json_path="$CONTRIBUTIONS_REPO/$dst_rel_json_path"
          if ! diff -u "$src_json_path" "$dst_json_path"; then
            if ! diff -u "$src_json_path" <(git -C "$CONTRIBUTIONS_REPO" show "$branch:$dst_rel_json_path"); then
              changed_from_branch=1
            fi
            rsync --archive --delete "$(dirname "$src_json_path")/" "$(dirname "$dst_json_path")/"
            git -C "$CONTRIBUTIONS_REPO" add "$(dirname "$dst_rel_json_path")"
            changes+=("$(jq --raw-output '.name + " " + .version' "$src_json_path")")
          fi
        done

        if [ "$changed_from_branch" = 1 ]; then
          message="$(ruby -e 'puts ARGV.join(", ")' -- "${changes[@]}")"

          git -C "$CONTRIBUTIONS_REPO" checkout -B "$branch"
          git -C "$CONTRIBUTIONS_REPO" \
              -c user.name="$(git log -1 --format=%an)" \
              -c user.email="$(git log -1 --format=%ae)" \
              commit --message "$message"
          git -C "$CONTRIBUTIONS_REPO" push --force rw HEAD

          pr_url="https://github.com/Kapeli/$CONTRIBUTIONS_REPO/compare/master...$owner:$CONTRIBUTIONS_REPO:$branch?quick_pull=1"
          gh issue create \
            --title "$message" \
            --body "$pr_url" \
            --assignee "$owner"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
    - name: commit changes to gh-pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        branch=gh-pages

        if git fetch --depth=1 origin "$branch"; then
          git branch "$branch" --track origin/"$branch"
          git symbolic-ref HEAD refs/heads/"$branch"
          git reset
        else
          git checkout --orphan "$branch"
          git rm -rf .
        fi

        touch .nojekyll
        bundle exec script/index > index.html

        git add -f .nojekyll html index.html
        if ! git diff --staged --quiet; then
          git commit -m "$(date)"
          git push origin "$branch"
        fi
